apiVersion: v1
data:
  blobs: |-
    [
      {
        "name": "edp-maven",
        "path": "/nexus-data/blobs/edp-maven"
      },
      {
        "name": "docker-registry",
        "path": "/nexus-data/blobs/docker-registry"
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.metaLabels" . | nindent 4 }}
  name: nexus-blobs