apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{ template "admin-routes.whitelist.annotation" . }}
  labels:
    app: nexus
    {{- include "nexus-operator.metaLabels" . | nindent 4 }}
  name: nexus
spec:
  host: {{ template "nexus.hostname" . }}
  path: {{ if .Values.nexus.basePath }}/{{ .Values.nexus.basePath }}{{ else }}/{{ end }}
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nexus
    weight: 100
  wildcardPolicy: None
status:
  ingress: []