apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmRoleBatch
metadata:
  name: nexus
  annotations:
    "helm.sh/resource-policy": keep
spec:
  realm: {{ .Values.keycloakIntegration.realm }}
  roles:
    - attributes: null
      composite: false
      composites: null
      description: cp-registry-admin-{{ .Release.Namespace }}
      name: cp-registry-admin-{{ .Release.Namespace }}
