apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: nexus
  {{- include "nexus-operator.metaLabels" . | nindent 4 }}
spec:
  ports:
    - name: docker-hosted-http
      port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP