apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  labels:
    app: nexus
    {{- include "nexus-operator.metaLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nexus.storage.size }}
  storageClassName: {{ template "nexus.storageClass" . }}
  volumeMode: Filesystem