apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.metaLabels" . | nindent 4 }}
  name: nexus
spec:
  ports:
    - name: nexus-http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: keycloak-proxy
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP
